[build]
  command = "WEATHER_API_PROXY_URL=/.netlify/functions/weather XWEATHER_ALERTS_PROXY_URL=/.netlify/functions/xweather-alerts npm run build"
  publish = "dist/weather-app"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
